# Generated by Django 5.2.12 on 2026-03-22 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="activities.activity",
            ),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="activities.category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activityparticipant",
            unique_together={("activity", "user")},
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["category"], name="activities__categor_f36a4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["start_datetime"], name="activities__start_d_5cbe5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["status"], name="activities__status_b1bb4f_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["organizer"], name="activities__organiz_336af7_idx"
            ),
        ),
    ]
