# Generated by Django 5.0.14 on 2026-08-17 18:13

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_social_features"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activityswipe",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="activityswipe",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="activityswipe",
            name="user",
        ),
        migrations.RemoveField(
            model_name="availabilitystatus",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="squadmember",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="squad",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="squad",
            name="members",
        ),
        migrations.RemoveField(
            model_name="squadmember",
            name="squad",
        ),
        migrations.RemoveField(
            model_name="squadmember",
            name="user",
        ),
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
                protected=True,
            ),
        ),
        migrations.DeleteModel(
            name="ActivityStory",
        ),
        migrations.DeleteModel(
            name="ActivitySwipe",
        ),
        migrations.DeleteModel(
            name="AvailabilityStatus",
        ),
        migrations.DeleteModel(
            name="Squad",
        ),
        migrations.DeleteModel(
            name="SquadMember",
        ),
    ]
