# Generated by Django 5.2.12 on 2026-03-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripPassenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["booked_at"],
            },
        ),
        migrations.CreateModel(
            name="TripStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("order", models.PositiveIntegerField()),
                ("estimated_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=30)),
                ("plate", models.CharField(max_length=20)),
                ("capacity", models.PositiveIntegerField(default=4)),
                ("photo", models.URLField(blank=True, default="")),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_name", models.CharField(max_length=300)),
                (
                    "origin_latitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "origin_longitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                ("destination_name", models.CharField(max_length=300)),
                (
                    "destination_latitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "destination_longitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                ("departure_time", models.DateTimeField()),
                ("estimated_arrival", models.DateTimeField(blank=True, null=True)),
                (
                    "price_per_passenger",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("available_seats", models.PositiveIntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["-departure_time"],
            },
        ),
    ]
