# Generated by Django 5.2.12 on 2026-03-23 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="organizer_payout",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount transferred to organizer via Connect",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="platform_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Platform fee (10% of amount)",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="ConnectAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_account_id", models.CharField(max_length=255, unique=True)),
                ("charges_enabled", models.BooleanField(default=False)),
                ("payouts_enabled", models.BooleanField(default=False)),
                ("onboarding_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
