# Generated by Django 5.0.14 on 2026-04-01 02:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mountain", "Mountain"),
                            ("water", "Water"),
                            ("air", "Air"),
                            ("survival", "Survival"),
                            ("road", "Road"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tagline", models.CharField(blank=True, default="", max_length=120)),
                ("description", models.TextField()),
                ("cover_image", models.URLField(blank=True, default="")),
                (
                    "location_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("member_count", models.PositiveIntegerField(default=0)),
                (
                    "activity_label",
                    models.CharField(blank=True, default="Weekly", max_length=50),
                ),
                (
                    "cadence_label",
                    models.CharField(blank=True, default="Weekly", max_length=50),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="JournalStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category_label",
                    models.CharField(
                        blank=True, default="Expedition Story", max_length=80
                    ),
                ),
                (
                    "region_label",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("summary", models.TextField()),
                ("body", models.TextField(blank=True, default="")),
                ("author_name", models.CharField(max_length=120)),
                ("cover_image", models.URLField(blank=True, default="")),
                ("featured_quote", models.TextField(blank=True, default="")),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=1, default=0, max_digits=8),
                ),
                ("elevation_m", models.PositiveIntegerField(default=0)),
                ("read_time_minutes", models.PositiveIntegerField(default=8)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_trending", models.BooleanField(default=False)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="RankBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("icon", models.CharField(default="award", max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("camping", "Camping"),
                            ("climbing", "Climbing"),
                            ("water_sports", "Water Sports"),
                            ("tech", "Tech"),
                            ("packs", "Packs"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New / Unused"),
                            ("excellent", "Excellent"),
                            ("good", "Good Condition"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
                ),
                (
                    "location_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("cover_image", models.URLField(blank=True, default="")),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gear_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SafetyChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gear_progress", models.PositiveIntegerField(default=0)),
                ("gear_target", models.PositiveIntegerField(default=10)),
                (
                    "route_status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("incomplete", "Incomplete"),
                            ("ready", "Ready"),
                        ],
                        default="incomplete",
                        max_length=20,
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("incomplete", "Incomplete"),
                            ("ready", "Ready"),
                        ],
                        default="incomplete",
                        max_length=20,
                    ),
                ),
                ("permits_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_checklist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SafetyLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SafetyStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expedition_protocol",
                    models.CharField(default="Expedition Protocol", max_length=120),
                ),
                (
                    "current_location",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("temperature_c", models.IntegerField(default=0)),
                ("wind_kmh", models.PositiveIntegerField(default=0)),
                ("visibility_m", models.PositiveIntegerField(default=0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("warning", "Warning"),
                            ("high", "High Risk"),
                        ],
                        default="green",
                        max_length=20,
                    ),
                ),
                (
                    "storm_warning",
                    models.CharField(blank=True, default="", max_length=220),
                ),
                (
                    "system_status",
                    models.CharField(default="All systems green", max_length=60),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRankProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Trail Seeker", max_length=120)),
                ("level", models.PositiveIntegerField(default=1)),
                ("current_xp", models.PositiveIntegerField(default=0)),
                ("next_level_xp", models.PositiveIntegerField(default=1000)),
                ("total_distance_km", models.PositiveIntegerField(default=0)),
                ("peak_elevation_m", models.PositiveIntegerField(default=0)),
                ("group_saves", models.PositiveIntegerField(default=0)),
                (
                    "next_unlock",
                    models.CharField(default="Advanced Trailmaster", max_length=120),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rank_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RankChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.CharField(max_length=220)),
                ("progress", models.PositiveIntegerField(default=0)),
                ("target", models.PositiveIntegerField(default=100)),
                (
                    "reward_label",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "rank_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges",
                        to="ecosystem.userrankprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CommunityMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="ecosystem.community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("community", "user")},
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("earned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holders",
                        to="ecosystem.rankbadge",
                    ),
                ),
                (
                    "rank_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="ecosystem.userrankprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["badge__display_order"],
                "unique_together": {("rank_profile", "badge")},
            },
        ),
    ]
