# Generated by Django 5.2.12 on 2026-03-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_verification_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avg_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
